name: 'PR Auto Update'
description: 'Creates automaticaly a PR updating Main branch changes to Homol Branch or creates a PR updating Homol changes to Dev.'
branding:
  icon: bell
  color: blue
env:
  DESTINATION_BRANCH: ${{ github.base_ref == 'main' && 'homol' || 'dev' }}
on:
  pull_request:
    branches:
      - homol
      - main
    types: [ closed ]
    
  workflow_dispatch:
jobs:          
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.DESTINATION_BRANCH }}

      - name: Preparing branch
        if: github.event.pull_request.merged == true
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git reset --hard ${{ github.base_ref }}
        
      - name: Creating Pull Request
        if: github.event.pull_request.merged == true
        uses: peter-evans/create-pull-request@v3
        id: GITHUB_RUN_ID
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update DEV with HOMOL
          title: 'Chore: Dump ${{ github.base_ref }} into ${{ env.DESTINATION_BRANCH }}'
          body: >
            Automated PR to dump ${{ github.base_ref }} into ${{ env.DESTINATION_BRANCH }}
          labels: beta, automated pr
          reviewers: RomuloLim
  
#       - name: Approve PR
#         uses: juliangruber/approve-pull-request-action@v1
#         with:
#           github-token: ${{ secrets.ACTION_SECRET }}
#           number: ${{ steps.demo-1.outputs.pull-request-number }}

#       - name: Merge PR
#         uses: juliangruber/merge-pull-request-action@v1
#         with:
#           github-token: ${{ secrets.ACTION_SECRET }}
#           number: ${{ steps.demo-1.outputs.pull-request-number }}
#           method: squash
